language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true


install:
    - ./.travis_install_nightly.sh

script:
    - ./.travis_test.sh

notifications:
  email:
    - mmeyer@trobz.com